### ISSUE TITLE
Function to compare two ranges

### ISSUE THREAD

**Issue by alexndlm** [akalongman/php-ip-tools#1]
Hello.
Can you implement this feature?

**Comment by akalongman** [comment]
Can you show me example, how that feature must work?

**Comment by alexndlm** [comment]
Ip::match('192.168.100._', '192.168._._');  //true
or
Ip::matchRange('192.168.100._', '192.168._._'); //true

**Comment by andysnell** [comment]
It looks like this issue was resolved last October.  If so, could you please close out the issue so it doesn't show up in this year's Hacktoberfest list?
