### ISSUE TITLE
Reserved Documentation Ranges

### ISSUE THREAD

**Issue by moebrowne** [akalongman/php-ip-tools#5]
There are ranges of IPs reserved solely for use in documentation.

The `isValid` will return `true` for these ranges. Is this expected behaviour, or would it be useful to have another method to check for these IPs?

IPv4 Ranges, [reference](https://tools.ietf.org/html/rfc5737):
- `192.0.2.0/24`
- `198.51.100.0/24`
- `203.0.113.0/24`

IPv6 Ranges, [reference](https://tools.ietf.org/html/rfc3849):
- `2001:DB8::/32`

**Comment by akalongman** [comment]
Yes, its ok
